In [1]:
import cvxopt, numpy, pandas
from cvxopt import matrix, solvers,glpk

In [2]:
Transpcost = matrix(numpy.random.randint(10, size=(3,3)))
Supply = matrix(numpy.random.randint(10, size=(1,3)))
Demand = matrix(numpy.random.randint(10, size=(1,3)))

In [3]:
print(Transpcost)
print(Supply)
print(Demand)

[ 5  2  8]
[ 2  7  0]
[ 7  1  4]

[ 7  6  2]

[ 9  1  5]



In [4]:
-np.eye(9)


NameError: name 'np' is not defined